### ISSUE TITLE
inc32 directories missing

### ISSUE THREAD

**Issue by mjsabin01** [Microsoft/openssl#10]
The ms\do_pack\* scripts have line:
xcopy inc32 vsout\package\include /h /k /r /e /i /y >nul

However, the inc32 directory does not exist in the project.

**Comment by khouzam** [comment]
Which branch and commit are you building?

**Comment by mjsabin01** [comment]
I am just syncing the head branch: commit cdecafb415749564fa7e685a11dd8137fb0baf0b

**Comment by khouzam** [comment]
I've fixed this. After merging the master branch, inc32 was removed and include has the proper headers.
