### ISSUE TITLE
OpenSSL 1.0.2c

### ISSUE THREAD

**Issue by drewbug** [Microsoft/openssl#14]
Is upgrading this fork planned?

**Comment by khouzam** [comment]
Yes, I hadn't seen that 1.0.2c had been released. I will merge in the changes this week.

**Comment by drewbug** [comment]
Terrific! Thank you, @khouzam!

**Comment by khouzam** [comment]
I've updated the branches to match the new 1.0.1 and 1.0.2 releases.

The latest tags are: OpenSSL_1_0_2c_WinRT and OpenSSL_1_0_1o_WinRT

**Comment by khouzam** [comment]
I've just updated the code with the latest changes for OpenSSL_1_0_2d_WinRT and OpenSSL_1_0_1p_WinRT after the release of the most recent patch.
