### ISSUE TITLE
Windows Store 8.1 projects don't build with VS2015

### ISSUE THREAD

**Issue by stammen** [Microsoft/openssl#16]
The Windows Store 8.1 projects generated by ms\do_vsprojects.bat don't build with Visual Studio 2015 if VS2013 is not installed. For example, the following error is produced by NT-Store-8.1-Dll-Unicode.vcxproj:

1>.\ms\winrt.cpp : fatal error C1107: could not find assembly 'Platform.winmd': please specify the assembly search path using /AI or by setting the LIBPATH environment variable

NT-Store-8.1-Dll-Unicode.vcxproj

**Comment by mattleibow** [comment]
Did anyone solve this one?

**Comment by khouzam** [comment]
I'll have to setup a machine without VS 2013 and repro. Gimme a couple of days.

**Comment by stammen** [comment]
The problem is in openssl/ms/do_vsprojects.bat at line 4

call ms\setVSVars.bat VS12VC
call "%_VS12VC%\vcvarsall" x86

Since VS 2013 is not installed this will fail. There needs to be a check for VS2015 then VS2013.

**Comment by khouzam** [comment]
Thanks. I'll fix that then.

**Comment by adiviness** [comment]
This should now be fixed in all three branches.
