### ISSUE TITLE
Could not find assembly 'Windows.winmd'

### ISSUE THREAD

**Issue by steerlink** [Microsoft/openssl#36]
**Summary**

Trying to build NT-Phone-8.1-Dll-Unicode.vcxproj in Release ARM fails with "could not find assembly 'Windows.winmd'...". 

Branch: OpenSSL_1_0_2_WinRT-stable
Tag: OpenSSL_1_0_2j_WinRT
VS: Professional 2015 Version 14.0.25425.01 Update 3

**Steps to Reproduce**

git clone -b OpenSSL_1_0_2_WinRT-stable https://github.com/Microsoft/openssl.git
cd openssl
git checkout tags/OpenSSL_1_0_2j_WinRT
ms\do_vsprojects.bat
"%VS140COMNTOOLS%vsvars32.bat"
cd ..
msbuild openssl\vsout\NT-Phone-8.1-Dll-Unicode\NT-Phone-8.1-Dll-Unicode.vcxproj /p:Configuration="Release" /p:Platform="ARM" /m

**Error**

C1107 "could not find assembly 'Windows.winmd': please specify the assembly search path using /Al or by setting the LIBPATH environment variable

**Notes**

I'm able to successfully build Release/Win32 of the same project. Also tag "OpenSSL_1_0_2h_WinRT" builds fine in Release/ARM.

**Comment by khouzam** [comment]
@steerlink 

I'm following your steps (copy and paste) but I'm not hitting this issue. Can you produce a detailed log and send it my way?

Thanks

**Comment by steerlink** [comment]
@khouzam 

Here are some logs from a run I did using VS 2015 Community.

[build_logs.zip](https://github.com/Microsoft/openssl/files/514216/build_logs.zip)

**Comment by khouzam** [comment]
Hi @steerlink 

The logs show that the environment is not found, can you try the following:

Start a Developer Command Prompt and build from there.
Get a log from the successful build and we can try to see what's different.

**Comment by steerlink** [comment]
@khouzam The logs I supplied were generated inside a developer command prompt.

**Comment by steerlink** [comment]
Discovered this which provides another way to build the libraries: https://github.com/sgrebnov/OpenSSL-WinRT-build
