### ISSUE TITLE
WinRT branch builds with errors

### ISSUE THREAD

**Issue by stammen** [Microsoft/openssl#4]
The current WinRT branch builds with errors. There is a bad comment at line 1384 in winrtcomponent.cpp and the following build errors also occur:

7>------ Build started: Project: NT-Phone-8.1-Dll-Unicode-testapp, Configuration: Release ARM ------
8>------ Build started: Project: NT-Store-8.1-Static-Unicode-testapp, Configuration: Release ARM ------
9>------ Build started: Project: NT-Store-8.1-Dll-Unicode-testapp, Configuration: Release ARM ------
10>------ Build started: Project: NT-Phone-8.1-Static-Unicode-testapp, Configuration: Release ARM ------
11>------ Build started: Project: NT-Phone-8.0-Static-Unicode-testapp, Configuration: Release ARM ------
12>------ Build started: Project: NT-Phone-8.0-Dll-Unicode-testapp, Configuration: Release ARM ------
9>d:\GitHub\openssl\ms\vstemplates\MainPage.xaml.cs(93,13,93,21): error CS0103: The name 'RunTests' does not exist in the current context
9>d:\GitHub\openssl\ms\vstemplates\MainPage.xaml.cs(99,13,99,21): error CS0103: The name 'RunTests' does not exist in the current context
8>d:\GitHub\openssl\ms\vstemplates\MainPage.xaml.cs(93,13,93,21): error CS0103: The name 'RunTests' does not exist in the current context
8>d:\GitHub\openssl\ms\vstemplates\MainPage.xaml.cs(99,13,99,21): error CS0103: The name 'RunTests' does not exist in the current context

**Comment by seecrypt** [comment]
Both these issues should be fixed with the latest commits that have been merged with the WinRT branch.

[Fixes winrtcomponent.cpp](https://github.com/Microsoft/openssl/commit/c20688d1d75ce91d492ade9a335ba889854f05f9)

[Fixes RunTests issue](https://github.com/Microsoft/openssl/commit/b2a3b85ae58c2b661d7c1330fc4ef8bbaa61533b)
