### ISSUE TITLE
uwp builds with nmake will fail WACK testing

### ISSUE THREAD

**Issue by stammen** [Microsoft/openssl#42]
When using ms/do_winuniversal.bat to set up a UWP build, the openssl dlls will fail WACK after building with nmake (ie. nmake -f ms\ntdll.mak)

The dlls fail WACK because the store option is missing from the call to vcvarsall in ms/setVSvars.bat,

	:set_universal10.0Win32
		call:setVar _VS14VC VisualStudio14VC
		call "%_VS14VC%vcvarsall" x86 store <-- missing store parameter
		set _VCPlatform=x86
		set _VCLibPlat=
		call:setEnv
		goto :eof
	

	:set_universal10.0x64
		call:setVar _VS14VC VisualStudio14VC
		call "%_VS14VC%vcvarsall" x64 store <-- missing store parameter
		set _VCPlatform=x64
		set _VCLibPlat=amd64
		call:setEnv
		goto :eof
	

	:set_universal10.0arm
		call:setVar _VS14VC VisualStudio14VC
		call "%_VS14VC%vcvarsall" x86_arm store <-- missing store parameter
		set _VCPlatform=ARM
		set _VCLibPlat=ARM
		call:setEnv
		goto :eof
	

	:set_universal10.0arm64
		call:setVar _VS14VC VisualStudio14VC
		call "%_VS14VC%vcvarsall" x86_arm64 store <-- missing store parameter
		set _VCPlatform=ARM64
		set _VCLibPlat=ARM64
		call:setEnv
		goto :eof

**Comment by khouzam** [comment]
Thanks @stammen,

We had purposefully omitted the store parameter because it had a bug in the initial VS2015 release when we initially created the fork. We should change this now that it is fixed.

**Comment by khouzam** [comment]
Updated for 1.0.1 and 1.0.2
ba2b26d4b50455c49506538a15cd9d677d5fd05a and 8bd2c5dfdb7bec3067ebf371a11c0a82bd08a8f4.

**Comment by stammen** [comment]
@khouzam Thanks!

**Comment by Petezah** [comment]
Just hit this myself.  Thanks @stammen and @khouzam !
