### ISSUE TITLE
Windows10Universal command line test

### ISSUE THREAD

**Issue by rajashanmugam83** [Microsoft/openssl#46]
I can able to compile using INSTALL.WINUNIVERSAL using below steps
> perl Configure no-asm no-hw no-dso VC-WINUNIVERSAL
> ms\do_winuniversal
> ms\setVSvars universal10.0Win32
 > nmake -f ms\nt.mak init
 > nmake -f ms\nt.mak

Now when i try to try to run the tests using command line
> nmake -f ms\nt.mak test
I am getting below error
        cd out32
        ..\ms\test
rsa_test
'rsa_test' is not recognized as an internal or external command,
operable program or batch file.
problems.....

I can able to run the tests using the Universal Test App project in Openssl.sln. 
Is it possible to run the tests using command line ?

**Comment by khouzam** [comment]
Hi @rajashanmugam83,

Command line applications are not supported as Universal Windows Applications, that's is why we've wrapped them in the Universal Test App. The same code is being executed just from within a UWP application.

**Comment by rajashanmugam83** [comment]
@khouzam 
Thanks for your clarification.
