### ISSUE TITLE
openssl.sln file will build using msbuild unless first opened in VS2013 then saved

### ISSUE THREAD

**Issue by jmspring** [Microsoft/openssl#5]
Execute: ms/do_vspackages.bat
Then execute: msbuild openssl.sln /property:Configuration="Debug";Platform="x86"

Result:
Microsoft (R) Build Engine version 12.0.31101.0
[Microsoft .NET Framework, version 4.0.30319.34014]
Copyright (C) Microsoft Corporation. All rights reserved.

Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
Build started 1/6/2015 7:33:18 AM.

Build succeeded.
    0 Warning(s)
    0 Error(s)

Time Elapsed 00:00:00.03

Opening the solution in VS2013 then saving it and redoing the msbuild step will build the configuration/platform.

**Comment by khouzam** [comment]
Thanks for the report Jim, I'll take a look.

**Comment by khouzam** [comment]
The latest update should take care of this issue. The dependencies were not written to the solution file.
