### ISSUE TITLE
 Bump OpenSSL to 1.0.2o

### ISSUE THREAD

**Issue by wangdevmgit** [Microsoft/openssl#54]
Hi, I find OpenSSL 1.0.2o is now available, is there any plan to bump OpenSSL 1.0.2n to 1.0.2o?

**Comment by khouzam** [comment]
I'll take a look at merging that in.

**Comment by MouriNaruto** [comment]
I have make a pull request (https://github.com/Microsoft/openssl/pull/56).

**Comment by khouzam** [comment]
Thanks @MouriNaruto 

Merged.
