### ISSUE TITLE
Fails Windows Store App Certification

### ISSUE THREAD

**Issue by wangdevmgit** [Microsoft/openssl#57]
I run a windows store certification kit to check my uwp app and got failed. The error is:

> API getenv in api-ms-win-crt-environment-l1-1-0.dll is not supported for this application type. libeay32.dll calls this API.

So I couldn't publish our UWP app with this version of OpenSSL. 

I guess the file ms\winrtdef.h cause this issue.

**Comment by khouzam** [comment]
Hi @wangdevmgit,

I had inadvertently removed the following two lines causing the failure (since one of them was clearly wrong). I'll put them back
```
# define getenv winrt_getenv
# define setenv winrt_getenv
```

**Comment by khouzam** [comment]
I've pushed the fix to OpenSSL_1_0_2_WinRT-stable
