### ISSUE TITLE
alleged "Static" projects still produce DLLs

### ISSUE THREAD

**Issue by amoldeshpande** [Microsoft/openssl#6]
nt.mak has dll output targets.

**Comment by khouzam** [comment]
Thanks. I'll take a look.

**Comment by khouzam** [comment]
The OpenSSL libraries are produced as static libraries (**ssleay32.lib** and **libeay32.lib**). The other files that are in the out32 folder are the tests binaries. We create tests dlls that get run inside our test app because we can't run command-line executables.

Are you seeing something else?

**Comment by amoldeshpande** [comment]
nope, I just misunderstood what the static projects meant. apologies.
