### ISSUE TITLE
OpenSSL 1.1.1 (LTS)

### ISSUE THREAD

**Issue by MouriNaruto** [Microsoft/openssl#65]
Hi, is there any plan to bump OpenSSL 1.0.2 to 1.1.1?

**Comment by khouzam** [comment]
That is on my list of things to do but is a much bigger change since a whole lot of things have changed between 1.0 and 1.1. It would almost be a brand new port inspired from the 1.0 one.

**Comment by MouriNaruto** [comment]
@khouzam Can you create a new branch which contains OpenSSL 1.1.1 for this repo? I want to help you adapt it via pulling requests, but no branch I can pull. (Sad.)

Mouri

**Comment by khouzam** [comment]
Hi @MouriNaruto,

I've create a new branch `develop/OpenSSL_1_1_1` which is based upon `OpenSSL_1_1_1-stable` where you can create pull requests.

Thank you for the help.

**Comment by MouriNaruto** [comment]
@khouzam Because I have seen some people done some work on the offical OpenSSL repo. So I add the support and try to pull request to the offical OpenSSL repo. (Because I think it can help more UWP developers.)

https://github.com/openssl/openssl/pull/7729

But I don't know how to make this PR merged by them successfully. So I think I need your help. Thanks.

Mouri.

**Comment by illera88** [comment]
how is this task going on? There are tons of libraries that have OpenSSL 1.1.X as dependency and it's stopping them from being able to be used at the moment.

**Comment by MouriNaruto** [comment]
@illera88 I have opened a new PR in the offical OpenSSL repo. (https://github.com/openssl/openssl/pull/8917)

**Comment by MouriNaruto** [comment]
Closed because of https://github.com/microsoft/openssl/issues/72.
