### ISSUE TITLE
A set of APIs from libeay32.dll does not pass Windows App Certification Kit Test

### ISSUE THREAD

**Issue by itsjehad** [Microsoft/openssl#7]
I am trying to create a Windows 8.1 store app which uses OpenSSL. These are the errors I am getting.

?API 1016 in libeay32.dll is not supported for this application type. my_pkcs.dll calls this API.
?API 1070 in libeay32.dll is not supported for this application type. my_pkcs.dll calls this API.
?API 1071 in libeay32.dll is not supported for this application type. my_pkcs.dll calls this API.
?API 109 in libeay32.dll is not supported for this application type. my_pkcs.dll calls this API.
?API 11 in libeay32.dll is not supported for this application type. my_pkcs.dll calls this API.
?API 1161 in libeay32.dll is not supported for this application type. my_pkcs.dll calls this API.
?API 1167 in libeay32.dll is not supported for this application type. my_pkcs.dll calls this API.
?API 118 in libeay32.dll is not supported for this application type. my_pkcs.dll calls this API.
?API 119 in libeay32.dll is not supported for this application type. my_pkcs.dll calls this API.
?API 1220 in libeay32.dll is not supported for this application type. my_pkcs.dll calls this API.
?API 1257 in libeay32.dll is not supported for this application type. my_pkcs.dll calls this API.
?API 129 in libeay32.dll is not supported for this application type. my_pkcs.dll calls this API.
?API 1291 in libeay32.dll is not supported for this application type. my_pkcs.dll calls this API.
?API 1304 in libeay32.dll is not supported for this application type. my_pkcs.dll calls this API.
?API 1305 in libeay32.dll is not supported for this application type. my_pkcs.dll calls this API.
?API 1306 in libeay32.dll is not supported for this application type. my_pkcs.dll calls this API.
?API 1308 in libeay32.dll is not supported for this application type. my_pkcs.dll calls this API.
?API 150 in libeay32.dll is not supported for this application type. my_pkcs.dll calls this API.
?API 161 in libeay32.dll is not supported for this application type. my_pkcs.dll calls this API.
?API 1653 in libeay32.dll is not supported for this application type. my_pkcs.dll calls this API.
?API 1654 in libeay32.dll is not supported for this application type. my_pkcs.dll calls this API.
?API 1795 in libeay32.dll is not supported for this application type. my_pkcs.dll calls this API.
?API 181 in libeay32.dll is not supported for this application type. my_pkcs.dll calls this API.
?API 1882 in libeay32.dll is not supported for this application type. my_pkcs.dll calls this API.
?API 1912 in libeay32.dll is not supported for this application type. my_pkcs.dll calls this API.
?API 1958 in libeay32.dll is not supported for this application type. my_pkcs.dll calls this API.
?API 1969 in libeay32.dll is not supported for this application type. my_pkcs.dll calls this API.
?API 2033 in libeay32.dll is not supported for this application type. my_pkcs.dll calls this API.
?API 2075 in libeay32.dll is not supported for this application type. my_pkcs.dll calls this API.
?API 2111 in libeay32.dll is not supported for this application type. my_pkcs.dll calls this API.
?API 22 in libeay32.dll is not supported for this application type. my_pkcs.dll calls this API.
?API 222 in libeay32.dll is not supported for this application type. my_pkcs.dll calls this API.
?API 223 in libeay32.dll is not supported for this application type. my_pkcs.dll calls this API.
?API 224 in libeay32.dll is not supported for this application type. my_pkcs.dll calls this API.
?API 227 in libeay32.dll is not supported for this application type. my_pkcs.dll calls this API.
?API 233 in libeay32.dll is not supported for this application type. my_pkcs.dll calls this API.
?API 2411 in libeay32.dll is not supported for this application type. my_pkcs.dll calls this API.
?API 2448 in libeay32.dll is not supported for this application type. my_pkcs.dll calls this API.
?API 2454 in libeay32.dll is not supported for this application type. my_pkcs.dll calls this API.
?API 246 in libeay32.dll is not supported for this application type. my_pkcs.dll calls this API.
?API 256 in libeay32.dll is not supported for this application type. my_pkcs.dll calls this API.
?API 2630 in libeay32.dll is not supported for this application type. my_pkcs.dll calls this API.
?API 2631 in libeay32.dll is not supported for this application type. my_pkcs.dll calls this API.
?API 2656 in libeay32.dll is not supported for this application type. my_pkcs.dll calls this API.
?API 266 in libeay32.dll is not supported for this application type. my_pkcs.dll calls this API.
?API 2660 in libeay32.dll is not supported for this application type. my_pkcs.dll calls this API.
?API 268 in libeay32.dll is not supported for this application type. my_pkcs.dll calls this API.
?API 269 in libeay32.dll is not supported for this application type. my_pkcs.dll calls this API.
?API 271 in libeay32.dll is not supported for this application type. my_pkcs.dll calls this API.
?API 272 in libeay32.dll is not supported for this application type. my_pkcs.dll calls this API.
?API 273 in libeay32.dll is not supported for this application type. my_pkcs.dll calls this API.
?API 276 in libeay32.dll is not supported for this application type. my_pkcs.dll calls this API.
?API 279 in libeay32.dll is not supported for this application type. my_pkcs.dll calls this API.
?API 281 in libeay32.dll is not supported for this application type. my_pkcs.dll calls this API.
?API 2821 in libeay32.dll is not supported for this application type. my_pkcs.dll calls this API.
?API 283 in libeay32.dll is not supported for this application type. my_pkcs.dll calls this API.
?API 289 in libeay32.dll is not supported for this application type. my_pkcs.dll calls this API.
?API 2894 in libeay32.dll is not supported for this application type. my_pkcs.dll calls this API.
?API 290 in libeay32.dll is not supported for this application type. my_pkcs.dll calls this API.
?API 2927 in libeay32.dll is not supported for this application type. my_pkcs.dll calls this API.
?API 2936 in libeay32.dll is not supported for this application type. my_pkcs.dll calls this API.
?API 298 in libeay32.dll is not supported for this application type. my_pkcs.dll calls this API.
?API 2996 in libeay32.dll is not supported for this application type. my_pkcs.dll calls this API.
?API 3019 in libeay32.dll is not supported for this application type. my_pkcs.dll calls this API.
?API 302 in libeay32.dll is not supported for this application type. my_pkcs.dll calls this API.
?API 3067 in libeay32.dll is not supported for this application type. my_pkcs.dll calls this API.
?API 3109 in libeay32.dll is not supported for this application type. my_pkcs.dll calls this API.
?API 3212 in libeay32.dll is not supported for this application type. my_pkcs.dll calls this API.
?API 323 in libeay32.dll is not supported for this application type. my_pkcs.dll calls this API.
?API 3245 in libeay32.dll is not supported for this application type. my_pkcs.dll calls this API.
?API 3253 in libeay32.dll is not supported for this application type. my_pkcs.dll calls this API.
?API 3286 in libeay32.dll is not supported for this application type. my_pkcs.dll calls this API.
?API 3312 in libeay32.dll is not supported for this application type. my_pkcs.dll calls this API.
?API 3313 in libeay32.dll is not supported for this application type. my_pkcs.dll calls this API.
?API 3315 in libeay32.dll is not supported for this application type. my_pkcs.dll calls this API.
?API 333 in libeay32.dll is not supported for this application type. my_pkcs.dll calls this API.
?API 355 in libeay32.dll is not supported for this application type. my_pkcs.dll calls this API.
?API 356 in libeay32.dll is not supported for this application type. my_pkcs.dll calls this API.
?API 357 in libeay32.dll is not supported for this application type. my_pkcs.dll calls this API.
?API 362 in libeay32.dll is not supported for this application type. my_pkcs.dll calls this API.
?API 366 in libeay32.dll is not supported for this application type. my_pkcs.dll calls this API.
?API 3686 in libeay32.dll is not supported for this application type. my_pkcs.dll calls this API.
?API 3844 in libeay32.dll is not supported for this application type. my_pkcs.dll calls this API.
?API 401 in libeay32.dll is not supported for this application type. my_pkcs.dll calls this API.
?API 4119 in libeay32.dll is not supported for this application type. my_pkcs.dll calls this API.
?API 4164 in libeay32.dll is not supported for this application type. my_pkcs.dll calls this API.
?API 421 in libeay32.dll is not supported for this application type. my_pkcs.dll calls this API.
?API 423 in libeay32.dll is not supported for this application type. my_pkcs.dll calls this API.
?API 4245 in libeay32.dll is not supported for this application type. my_pkcs.dll calls this API.
?API 4430 in libeay32.dll is not supported for this application type. my_pkcs.dll calls this API.
?API 464 in libeay32.dll is not supported for this application type. my_pkcs.dll calls this API.
?API 469 in libeay32.dll is not supported for this application type. my_pkcs.dll calls this API.
?API 484 in libeay32.dll is not supported for this application type. my_pkcs.dll calls this API.
?API 486 in libeay32.dll is not supported for this application type. my_pkcs.dll calls this API.
?API 493 in libeay32.dll is not supported for this application type. my_pkcs.dll calls this API.
?API 497 in libeay32.dll is not supported for this application type. my_pkcs.dll calls this API.
?API 509 in libeay32.dll is not supported for this application type. my_pkcs.dll calls this API.
?API 510 in libeay32.dll is not supported for this application type. my_pkcs.dll calls this API.
?API 52 in libeay32.dll is not supported for this application type. my_pkcs.dll calls this API.
?API 566 in libeay32.dll is not supported for this application type. my_pkcs.dll calls this API.
?API 567 in libeay32.dll is not supported for this application type. my_pkcs.dll calls this API.
?API 575 in libeay32.dll is not supported for this application type. my_pkcs.dll calls this API.
?API 576 in libeay32.dll is not supported for this application type. my_pkcs.dll calls this API.
?API 577 in libeay32.dll is not supported for this application type. my_pkcs.dll calls this API.
?API 578 in libeay32.dll is not supported for this application type. my_pkcs.dll calls this API.
?API 581 in libeay32.dll is not supported for this application type. my_pkcs.dll calls this API.
?API 585 in libeay32.dll is not supported for this application type. my_pkcs.dll calls this API.
?API 600 in libeay32.dll is not supported for this application type. my_pkcs.dll calls this API.
?API 602 in libeay32.dll is not supported for this application type. my_pkcs.dll calls this API.
?API 605 in libeay32.dll is not supported for this application type. my_pkcs.dll calls this API.
?API 606 in libeay32.dll is not supported for this application type. my_pkcs.dll calls this API.
?API 607 in libeay32.dll is not supported for this application type. my_pkcs.dll calls this API.
?API 608 in libeay32.dll is not supported for this application type. my_pkcs.dll calls this API.
?API 623 in libeay32.dll is not supported for this application type. my_pkcs.dll calls this API.
?API 624 in libeay32.dll is not supported for this application type. my_pkcs.dll calls this API.
?API 626 in libeay32.dll is not supported for this application type. my_pkcs.dll calls this API.
?API 628 in libeay32.dll is not supported for this application type. my_pkcs.dll calls this API.
?API 629 in libeay32.dll is not supported for this application type. my_pkcs.dll calls this API.
?API 641 in libeay32.dll is not supported for this application type. my_pkcs.dll calls this API.
?API 653 in libeay32.dll is not supported for this application type. my_pkcs.dll calls this API.
?API 654 in libeay32.dll is not supported for this application type. my_pkcs.dll calls this API.
?API 656 in libeay32.dll is not supported for this application type. my_pkcs.dll calls this API.
?API 657 in libeay32.dll is not supported for this application type. my_pkcs.dll calls this API.
?API 66 in libeay32.dll is not supported for this application type. my_pkcs.dll calls this API.
?API 67 in libeay32.dll is not supported for this application type. my_pkcs.dll calls this API.
?API 679 in libeay32.dll is not supported for this application type. my_pkcs.dll calls this API.
?API 680 in libeay32.dll is not supported for this application type. my_pkcs.dll calls this API.
?API 748 in libeay32.dll is not supported for this application type. my_pkcs.dll calls this API.
?API 749 in libeay32.dll is not supported for this application type. my_pkcs.dll calls this API.
?API 754 in libeay32.dll is not supported for this application type. my_pkcs.dll calls this API.
?API 78 in libeay32.dll is not supported for this application type. my_pkcs.dll calls this API.
?API 82 in libeay32.dll is not supported for this application type. my_pkcs.dll calls this API.
?API 851 in libeay32.dll is not supported for this application type. my_pkcs.dll calls this API.
?API 852 in libeay32.dll is not supported for this application type. my_pkcs.dll calls this API.
?API 871 in libeay32.dll is not supported for this application type. my_pkcs.dll calls this API.
?API 877 in libeay32.dll is not supported for this application type. my_pkcs.dll calls this API.
?API 89 in libeay32.dll is not supported for this application type. my_pkcs.dll calls this API.
?API 9 in libeay32.dll is not supported for this application type. my_pkcs.dll calls this API.
?API 909 in libeay32.dll is not supported for this application type. my_pkcs.dll calls this API.
?API 910 in libeay32.dll is not supported for this application type. my_pkcs.dll calls this API.
?API 917 in libeay32.dll is not supported for this application type. my_pkcs.dll calls this API.
?API 93 in libeay32.dll is not supported for this application type. my_pkcs.dll calls this API.
?API 95 in libeay32.dll is not supported for this application type. my_pkcs.dll calls this API.
?API 961 in libeay32.dll is not supported for this application type. my_pkcs.dll calls this API.
?API 74 in ssleay32.dll is not supported for this application type. my_pkcs.dll calls this API.

Any thoughts?

**Comment by khouzam** [comment]
Hi itsjehad,

Can you create a small repro for us to look at? How have you built the OpenSSL dlls?

**Comment by itsjehad** [comment]
I used vsout\OpenSSL.sln generated by ms\do_vsprojects.bat. 
Compiled the VC project, NT-Store-8.1-Dll-Unicode-winrtcomponent. 
Copy both (libeay32 and ssleay32) libs and dlls from "Openssl-WinRT\vsout\NT-Store-8.1-Dll-Unicode\Release\Win32\bin" to my project's work space. 
Compiled and tested my project with "Windows App Certification Kit". 
Finally got the APIs not supported errors. 
Thanks,

**Comment by itsjehad** [comment]
These are some of the APIs we used,

API 1016 (X509_STORE_CTX_get_error) in libeay32.dll.
API 1070(EVP_PKEY_decrypt)  in libeay32.dll.
API 1071 (EVP_PKEY_encrypt) in libeay32.dll.
API 109 (BIO_write) in libeay32.dll.
API 11 (ASN1_OBJECT_free) in libeay32.dll.

**Comment by khouzam** [comment]
I've taken a clean image of our WinRT branch, created the projects with ms\do_vsprojects.bat, built the test app and submitted to the App Certification Kit. The only API violations that were raised were OutputDebugString in WinRTComponent.cpp which is not part of libeay.dll or ssleay.dll.

Can you send me a private email? I'd like to dig deeper into this issue.

**Comment by itsjehad** [comment]
My system messed out with the DLLs, i guess. It has passed the certification test now... I am sorry for the inconvenience.
