### ISSUE TITLE
Do we have plan to create openssl 1.0.2r branch for UWP platform?

### ISSUE THREAD

**Issue by higarry** [Microsoft/openssl#71]
Hi,

As the title mentioned, do we have plan to create a new branch for 1.0.2r ?

Thanks

**Comment by MouriNaruto** [comment]
https://github.com/openssl/openssl/pull/7729

I had made some effort to the offical OpenSSL. Hope it will be merged.

Mouri

**Comment by stammen** [comment]
1.0.2r has been merged into 1.0.2 winrt stable branch,
