### ISSUE TITLE
error build openssl NT-Store-8.1-Dll

### ISSUE THREAD

**Issue by sggeng** [Microsoft/openssl#8]
Here's the error message:

Error   214 error C1107: could not find assembly 'windows.foundation.foundationcontract.winmd': please specify the assembly search path using /AI or by setting the LIBPATH environment variable    C:\Sherman\ReferenceProjects\C++\openssl-WinRT\vsout\NT-Store-8.1-Dll-Unicode\ms\winrt.cpp  NT-Store-8.1-Dll-Unicode

**Comment by khouzam** [comment]
Thanks for reporting this. Our update for the new Windows 10 tools has introduced this break.

I have pushed out a fix for this. Both Win10 and Win8.1 now build properly.

**Comment by sggeng** [comment]
verified problem is fixed.
