### ISSUE TITLE
Build error in ARM / Release configuration

### ISSUE THREAD

**Issue by mjsabin01** [Microsoft/openssl#9]
I am running into issues building the ARM Release configurations:

Static-Unicode:
All packages are already installed and there is nothing to restore.
NuGet package restore finished.
1>------ Build started: Project: NT-Universal-10.0-Static-Unicode, Configuration: Release ARM ------
1>  10.0.10069.0
1>
1>  Microsoft (R) Program Maintenance Utility Version 14.00.22816.0
1>  Copyright (C) Microsoft Corporation.  All rights reserved.
1>
1>
1>  Microsoft (R) Program Maintenance Utility Version 14.00.22816.0
1>  Copyright (C) Microsoft Corporation.  All rights reserved.
1>
1>  Building OpenSSL
1>      link /dll /EXPORT:winrt_main /nologo /APPCONTAINER "WindowsApp.lib" /debug /out:vsout\NT-Universal-10.0-Static-Unicode\Release\arm\bin\bftest.dll @C:\Users\MICHAE~1\AppData\Local\Temp\nm4B3D.tmp
1>     Creating library vsout\NT-Universal-10.0-Static-Unicode\Release\arm\bin\bftest.lib and object vsout\NT-Universal-10.0-Static-Unicode\Release\arm\bin\bftest.exp
1>LINK : fatal error LNK1101: incorrect MSPDB140.DLL version; recheck installation of this product
1>NMAKE : fatal error U1077: '"C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\x86_ARM\link.EXE"' : return code '0x44d'
1>  Stop.
1>C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.MakeFile.Targets(42,5): error MSB3073: The command "build.bat Release ARM" exited with code 2.
========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========

Dll-Unicode:
All packages are already installed and there is nothing to restore.
NuGet package restore finished.
1>------ Build started: Project: NT-Universal-10.0-Dll-Unicode, Configuration: Release ARM ------
1>  10.0.10069.0
1>
1>  Microsoft (R) Program Maintenance Utility Version 14.00.22816.0
1>  Copyright (C) Microsoft Corporation.  All rights reserved.
1>
1>
1>  Microsoft (R) Program Maintenance Utility Version 14.00.22816.0
1>  Copyright (C) Microsoft Corporation.  All rights reserved.
1>
1>  Building OpenSSL
1>      link /nologo /APPCONTAINER "WindowsApp.lib" /debug /dll /out:vsout\NT-Universal-10.0-Dll-Unicode\Release\arm\bin\libeay32.dll /def:ms/LIBEAY32.def @C:\Users\MICHAE~1\AppData\Local\Temp\nmE7C7.tmp
1>vsout\NT-Universal-10.0-Dll-Unicode\Release\arm\tmp\winrt.obj : warning LNK4042: object specified more than once; extras ignored
1>     Creating library vsout\NT-Universal-10.0-Dll-Unicode\Release\arm\bin\libeay32.lib and object vsout\NT-Universal-10.0-Dll-Unicode\Release\arm\bin\libeay32.exp
1>LINK : fatal error LNK1101: incorrect MSPDB140.DLL version; recheck installation of this product
1>NMAKE : fatal error U1077: '"C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\x86_ARM\link.EXE"' : return code '0x44d'
1>  Stop.
1>C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.MakeFile.Targets(42,5): error MSB3073: The command "build.bat Release ARM" exited with code 2.
========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========

**Comment by khouzam** [comment]
Thanks for reporting this. I've seen this as an intermittent issue on the current build of VS 2015 RC. I'm trying to understand the root cause as I'm also seeing it on other projects.

**Comment by khouzam** [comment]
There seems to be an issue with VS 2015 RC. I've notified the VS team about it. In the meantime, you can get around the issue by running the following command on an Admin command prompt.

copy "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\bin\mspdbsrv.exe" "C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE"

**Comment by mjsabin01** [comment]
Thanks, that worked.
